import mongoose, { Document, Schema } from "mongoose";

export interface IBlog extends Document {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  category: mongoose.Types.ObjectId;
  categoryName: string;
  tags: string[];
  metaTitle: string;
  metaDescription: string;
  focusKeyword: string;
  keywords: string[];
  readTime: number;
  coverImage: string;
  isPublished: boolean;
  isAutoGenerated: boolean;
  views: number;
  author: string;
  publishedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

const BlogSchema = new Schema<IBlog>(
  {
    title: { type: String, required: true, trim: true },
    slug: { type: String, required: true, unique: true, lowercase: true },
    excerpt: { type: String, required: true, maxlength: 300 },
    content: { type: String, required: true },
    category: { type: Schema.Types.ObjectId, ref: "Category", required: true },
    categoryName: { type: String, required: true },
    tags: [{ type: String }],
    metaTitle: { type: String, maxlength: 70 },
    metaDescription: { type: String, maxlength: 160 },
    focusKeyword: { type: String },
    keywords: [{ type: String }],
    readTime: { type: Number, default: 5 },
    coverImage: { type: String, default: "" },
    isPublished: { type: Boolean, default: true },
    isAutoGenerated: { type: Boolean, default: true },
    views: { type: Number, default: 0 },
    author: { type: String, default: "ByteMind Editorial" },
    publishedAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

BlogSchema.index({ category: 1 });
BlogSchema.index({ tags: 1 });
BlogSchema.index({ publishedAt: -1 });
BlogSchema.index({ focusKeyword: "text", title: "text", content: "text" });

export default mongoose.model<IBlog>("Blog", BlogSchema);
