"use client";
import { useEffect, useState } from "react";
import { useAdminStore } from "@/store/useAdminStore";
import { formatDate } from "@/lib/utils";
import Loading from "@/components/ui/Loading";
import { FiTrash2, FiEye, FiEyeOff, FiSearch, FiZap } from "react-icons/fi";

export default function AdminBlogsPage() {
  const { blogs, pagination, isLoading, fetchBlogs, deleteBlog, toggleBlog } = useAdminStore();
  const [page, setPage] = useState(1);
  const [confirmDelete, setConfirmDelete] = useState<string | null>(null);

  useEffect(() => {
    fetchBlogs({ page, limit: 15 });
  }, [page, fetchBlogs]);

  const handleDelete = async (id: string) => {
    await deleteBlog(id);
    setConfirmDelete(null);
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-black text-text-primary">All Articles</h1>
          <p className="text-text-muted mt-1">{pagination?.total || 0} total articles</p>
        </div>
      </div>

      {isLoading ? (
        <Loading />
      ) : (
        <div className="glass-card overflow-hidden">
          <table className="w-full">
            <thead>
              <tr className="border-b border-bg-border">
                <th className="text-left px-6 py-4 text-xs font-semibold text-text-muted uppercase tracking-wider">Title</th>
                <th className="text-left px-6 py-4 text-xs font-semibold text-text-muted uppercase tracking-wider hidden md:table-cell">Category</th>
                <th className="text-left px-6 py-4 text-xs font-semibold text-text-muted uppercase tracking-wider hidden lg:table-cell">Published</th>
                <th className="text-left px-6 py-4 text-xs font-semibold text-text-muted uppercase tracking-wider hidden sm:table-cell">Views</th>
                <th className="text-left px-6 py-4 text-xs font-semibold text-text-muted uppercase tracking-wider">Status</th>
                <th className="text-right px-6 py-4 text-xs font-semibold text-text-muted uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-bg-border">
              {blogs.map((blog) => (
                <tr key={blog._id} className="hover:bg-bg-secondary/50 transition-colors group">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      {blog.isAutoGenerated && (
                        <FiZap className="w-3 h-3 text-yellow-400 flex-shrink-0" title="AI Generated" />
                      )}
                      <p className="text-sm font-medium text-text-primary line-clamp-1 max-w-xs">{blog.title}</p>
                    </div>
                  </td>
                  <td className="px-6 py-4 hidden md:table-cell">
                    <span className="text-xs text-text-muted">{blog.categoryName}</span>
                  </td>
                  <td className="px-6 py-4 hidden lg:table-cell">
                    <span className="text-xs text-text-muted">{formatDate(blog.publishedAt)}</span>
                  </td>
                  <td className="px-6 py-4 hidden sm:table-cell">
                    <span className="text-xs text-text-muted">{blog.views}</span>
                  </td>
                  <td className="px-6 py-4">
                    <span className={`inline-flex items-center gap-1 text-xs px-2.5 py-1 rounded-full font-medium ${
                      blog.isPublished ? "bg-green-500/10 text-green-400" : "bg-red-500/10 text-red-400"
                    }`}>
                      <span className={`w-1.5 h-1.5 rounded-full ${blog.isPublished ? "bg-green-400" : "bg-red-400"}`} />
                      {blog.isPublished ? "Published" : "Draft"}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center justify-end gap-2">
                      <button
                        onClick={() => toggleBlog(blog._id)}
                        className="p-2 rounded-lg text-text-muted hover:text-accent-cyan hover:bg-accent-cyan/10 transition-all"
                        title={blog.isPublished ? "Unpublish" : "Publish"}
                      >
                        {blog.isPublished ? <FiEyeOff className="w-4 h-4" /> : <FiEye className="w-4 h-4" />}
                      </button>
                      {confirmDelete === blog._id ? (
                        <div className="flex gap-1">
                          <button
                            onClick={() => handleDelete(blog._id)}
                            className="text-xs px-2 py-1 bg-red-500 text-white rounded-lg hover:bg-red-600 transition-colors"
                          >
                            Delete
                          </button>
                          <button
                            onClick={() => setConfirmDelete(null)}
                            className="text-xs px-2 py-1 bg-bg-border text-text-muted rounded-lg hover:bg-bg-secondary transition-colors"
                          >
                            Cancel
                          </button>
                        </div>
                      ) : (
                        <button
                          onClick={() => setConfirmDelete(blog._id)}
                          className="p-2 rounded-lg text-text-muted hover:text-red-400 hover:bg-red-500/10 transition-all"
                        >
                          <FiTrash2 className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {!blogs.length && !isLoading && (
            <div className="text-center py-16">
              <p className="text-text-muted">No articles found. Generate some from the dashboard!</p>
            </div>
          )}
        </div>
      )}

      {pagination && pagination.pages > 1 && (
        <div className="flex justify-center gap-2 mt-6">
          <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1} className="px-4 py-2 rounded-lg bg-bg-card border border-bg-border text-sm text-text-secondary disabled:opacity-40 hover:border-accent-purple transition-all">← Prev</button>
          <span className="px-4 py-2 text-sm text-text-muted">Page {page} of {pagination.pages}</span>
          <button onClick={() => setPage(p => Math.min(pagination.pages, p + 1))} disabled={page === pagination.pages} className="px-4 py-2 rounded-lg bg-bg-card border border-bg-border text-sm text-text-secondary disabled:opacity-40 hover:border-accent-purple transition-all">Next →</button>
        </div>
      )}
    </div>
  );
}
