import cron from "node-cron";
import Category from "../models/Category";
import Blog from "../models/Blog";
import { generateBlogPost } from "./groqService";
import { createSlug, calculateReadTime } from "../utils/slugify";

const COVER_IMAGES: Record<string, string[]> = {
  "artificial-intelligence": [
    "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200",
    "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200",
  ],
  "machine-learning": [
    "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=1200",
    "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200",
  ],
  "programming": [
    "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200",
    "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200",
  ],
  "cybersecurity": [
    "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200",
    "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200",
  ],
  "gadgets": [
    "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1200",
    "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200",
  ],
  "cloud-devops": [
    "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200",
    "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200",
  ],
  "tech-news": [
    "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200",
    "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=1200",
  ],
  "ai-tools": [
    "https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200",
    "https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=1200",
  ],
};

const getRandomImage = (categorySlug: string): string => {
  const images = COVER_IMAGES[categorySlug] || [
    "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200",
  ];
  return images[Math.floor(Math.random() * images.length)];
};

const AUTHORS = [
  "Aryan Mehta",
  "Priya Sharma",
  "Rohan Verma",
  "Sneha Kapoor",
  "Dev Patel",
  "Ritik Kumar",
  "Ananya Singh",
  "Karan Joshi",
];

const pickAuthor = () => AUTHORS[Math.floor(Math.random() * AUTHORS.length)];

export const generateBlogForCategory = async (categoryId: string) => {
  const category = await Category.findById(categoryId);
  if (!category || !category.isActive) return;

  console.log(`🤖 Generating blog for: ${category.name}`);

  const generated = await generateBlogPost(category.name, category.slug);

  const baseSlug = createSlug(generated.title);
  const timestamp = Date.now().toString(36);
  const slug = `${baseSlug}-${timestamp}`;

  const truncate = (str: string, max: number) =>
    str && str.length > max ? str.slice(0, max - 1).trimEnd() + "…" : str;

  const blog = new Blog({
    title: truncate(generated.title, 150),
    slug,
    excerpt: truncate(generated.excerpt, 300),
    content: generated.content,
    category: category._id,
    categoryName: category.name,
    tags: (generated.tags || []).slice(0, 8),
    metaTitle: truncate(generated.metaTitle || generated.title, 70),
    metaDescription: truncate(generated.metaDescription || generated.excerpt, 160),
    focusKeyword: generated.focusKeyword,
    keywords: generated.keywords || [],
    readTime: calculateReadTime(generated.content),
    coverImage: getRandomImage(category.slug),
    isPublished: false,
    isAutoGenerated: true,
    author: pickAuthor(),
    publishedAt: new Date(),
  });

  await blog.save();
  await Category.findByIdAndUpdate(categoryId, { $inc: { blogCount: 1 } });

  console.log(`✅ Blog published: "${generated.title}" in ${category.name}`);
  return blog;
};

export const runManualGeneration = async () => {
  const categories = await Category.find({ isActive: true });
  const results = [];
  for (const cat of categories) {
    try {
      const blog = await generateBlogForCategory(cat._id.toString());
      results.push({ category: cat.name, success: true, blog });
    } catch (err) {
      console.error(`❌ Failed for ${cat.name}:`, err);
      results.push({ category: cat.name, success: false, error: String(err) });
    }
  }
  return results;
};

export const startScheduler = () => {
  // Runs every day at midnight (00:00)
  cron.schedule("0 0 * * *", async () => {
    console.log("⏰ Midnight cron triggered — generating daily blogs...");
    const categories = await Category.find({ isActive: true });
    for (const cat of categories) {
      try {
        await generateBlogForCategory(cat._id.toString());
        await new Promise((r) => setTimeout(r, 3000));
      } catch (err) {
        console.error(`❌ Scheduler error for ${cat.name}:`, err);
      }
    }
    console.log("🎉 Daily blog generation complete!");
  }, { timezone: "Asia/Kolkata" });

  console.log("⏰ Cron scheduler started — blogs post daily at midnight IST");
};
