export interface Category {
  _id: string;
  name: string;
  slug: string;
  description: string;
  color: string;
  icon: string;
  isActive: boolean;
  blogCount: number;
  createdAt: string;
}

export interface Blog {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  content?: string;
  category: Category | string;
  categoryName: string;
  tags: string[];
  metaTitle?: string;
  metaDescription?: string;
  focusKeyword?: string;
  keywords?: string[];
  readTime: number;
  coverImage: string;
  isPublished: boolean;
  isAutoGenerated: boolean;
  views: number;
  author: string;
  publishedAt: string;
  createdAt: string;
}

export interface Pagination {
  total: number;
  page: number;
  limit: number;
  pages: number;
}

export interface AdminStats {
  totalBlogs: number;
  totalCategories: number;
  totalViews: number;
  recentBlogs: Pick<Blog, "_id" | "title" | "categoryName" | "views" | "publishedAt">[];
}
