import { Router, Request, Response } from "express";
import jwt from "jsonwebtoken";
import Admin from "../models/Admin";
import Blog from "../models/Blog";
import Category from "../models/Category";
import { protect, AuthRequest } from "../middleware/authMiddleware";
import { generateBlogForCategory, runManualGeneration } from "../services/schedulerService";
import { humanizeBlogContent } from "../services/humanizeService";
import { createSlug } from "../utils/slugify";

const router = Router();

router.post("/login", async (req: Request, res: Response) => {
  try {
    const { email, password } = req.body;
    const admin = await Admin.findOne({ email });
    if (!admin || !(await admin.comparePassword(password))) {
      res.status(401).json({ success: false, message: "Invalid credentials" });
      return;
    }
    const token = jwt.sign({ id: admin._id }, process.env.JWT_SECRET!, { expiresIn: "7d" });
    res.json({ success: true, token, admin: { email: admin.email, name: admin.name } });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.get("/stats", protect, async (_req: AuthRequest, res: Response) => {
  try {
    const [totalBlogs, totalCategories, totalViews] = await Promise.all([
      Blog.countDocuments({ isPublished: true }),
      Category.countDocuments({ isActive: true }),
      Blog.aggregate([{ $group: { _id: null, total: { $sum: "$views" } } }]),
    ]);
    const recentBlogs = await Blog.find({ isPublished: true })
      .sort({ publishedAt: -1 })
      .limit(5)
      .select("title categoryName views publishedAt");

    res.json({
      success: true,
      data: {
        totalBlogs,
        totalCategories,
        totalViews: totalViews[0]?.total || 0,
        recentBlogs,
      },
    });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.get("/blogs", protect, async (req: AuthRequest, res: Response) => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 10;
    const total = await Blog.countDocuments();
    const blogs = await Blog.find()
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit)
      .select("title categoryName isPublished views publishedAt isAutoGenerated");
    res.json({ success: true, data: blogs, pagination: { total, page, limit, pages: Math.ceil(total / limit) } });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.get("/drafts", protect, async (_req: AuthRequest, res: Response) => {
  try {
    const drafts = await Blog.find({ isPublished: false })
      .sort({ createdAt: -1 })
      .select("title categoryName excerpt readTime coverImage author createdAt focusKeyword tags");
    res.json({ success: true, data: drafts });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.get("/blogs/:id/full", protect, async (req: AuthRequest, res: Response) => {
  try {
    const blog = await Blog.findById(req.params.id).populate("category", "name slug color icon");
    if (!blog) { res.status(404).json({ success: false, message: "Not found" }); return; }
    res.json({ success: true, data: blog });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.put("/blogs/:id", protect, async (req: AuthRequest, res: Response) => {
  try {
    const { title, content, excerpt, metaTitle, metaDescription, tags, author } = req.body;
    const blog = await Blog.findByIdAndUpdate(
      req.params.id,
      { title, content, excerpt, metaTitle, metaDescription, tags, author },
      { new: true, runValidators: true }
    );
    if (!blog) { res.status(404).json({ success: false, message: "Not found" }); return; }
    res.json({ success: true, data: blog });
  } catch (err) {
    res.status(500).json({ success: false, message: String(err) });
  }
});

router.post("/blogs/:id/publish", protect, async (req: AuthRequest, res: Response) => {
  try {
    const blog = await Blog.findByIdAndUpdate(
      req.params.id,
      { isPublished: true, publishedAt: new Date() },
      { new: true }
    );
    if (!blog) { res.status(404).json({ success: false, message: "Not found" }); return; }
    res.json({ success: true, data: blog });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.post("/blogs/:id/humanize", protect, async (req: AuthRequest, res: Response) => {
  try {
    const blog = await Blog.findById(req.params.id);
    if (!blog) { res.status(404).json({ success: false, message: "Not found" }); return; }
    console.log(`✍️  Humanizing: "${blog.title}"`);
    const humanized = await humanizeBlogContent(blog.title, blog.content, blog.author);
    const truncate = (s: string, n: number) => s && s.length > n ? s.slice(0, n - 1) + "…" : s;
    blog.title = humanized.title || blog.title;
    blog.content = humanized.content || blog.content;
    blog.excerpt = truncate(humanized.excerpt || blog.excerpt, 300);
    await blog.save();
    console.log(`✅  Humanized: "${blog.title}"`);
    res.json({ success: true, data: blog });
  } catch (err) {
    console.error("Humanize error:", err);
    res.status(500).json({ success: false, message: String(err) });
  }
});

router.delete("/blogs/:id", protect, async (req: AuthRequest, res: Response) => {
  try {
    const blog = await Blog.findByIdAndDelete(req.params.id);
    if (!blog) { res.status(404).json({ success: false, message: "Blog not found" }); return; }
    await Category.findByIdAndUpdate(blog.category, { $inc: { blogCount: -1 } });
    res.json({ success: true, message: "Blog deleted" });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.patch("/blogs/:id/toggle", protect, async (req: AuthRequest, res: Response) => {
  try {
    const blog = await Blog.findById(req.params.id);
    if (!blog) { res.status(404).json({ success: false, message: "Blog not found" }); return; }
    blog.isPublished = !blog.isPublished;
    await blog.save();
    res.json({ success: true, data: blog });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.get("/categories", protect, async (_req: AuthRequest, res: Response) => {
  try {
    const categories = await Category.find().sort({ createdAt: -1 });
    res.json({ success: true, data: categories });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.post("/categories", protect, async (req: AuthRequest, res: Response) => {
  try {
    const { name, description, color, icon } = req.body;
    const slug = createSlug(name);
    const category = new Category({ name, slug, description, color, icon });
    await category.save();
    res.status(201).json({ success: true, data: category });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.delete("/categories/:id", protect, async (req: AuthRequest, res: Response) => {
  try {
    await Category.findByIdAndDelete(req.params.id);
    res.json({ success: true, message: "Category deleted" });
  } catch {
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.post("/rewrite-all", protect, async (_req: AuthRequest, res: Response) => {
  const truncate = (s: string, n: number) => s && s.length > n ? s.slice(0, n - 1) + "…" : s;

  // Extract retry-after seconds from Groq 429 error message
  const parseRetryAfter = (errMsg: string): number | null => {
    const m = errMsg.match(/Please try again in (\d+)h?(\d+)?m?(\d+(?:\.\d+)?)?s/);
    if (!m) return null;
    const hours = parseInt(m[1]) || 0;
    const mins  = parseInt(m[2]) || 0;
    const secs  = parseFloat(m[3]) || 0;
    return hours * 3600 + mins * 60 + Math.ceil(secs) + 5;
  };

  const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));

  const humanizeWithRetry = async (title: string, content: string, author: string, maxRetries = 3) => {
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        return await humanizeBlogContent(title, content, author);
      } catch (err) {
        const msg = String(err);
        if (msg.includes("429") && attempt < maxRetries) {
          const waitSecs = parseRetryAfter(msg) || 120;
          console.log(`  ⏳  Rate limited. Waiting ${waitSecs}s before retry ${attempt + 1}/${maxRetries}…`);
          await wait(waitSecs * 1000);
        } else {
          throw err;
        }
      }
    }
  };

  try {
    // Skip blogs already at good quality (>= 1000 words with 70b content)
    const blogs = await Blog.find({}).select("_id title content author");
    const pending = blogs.filter((b) => {
      const words = (b.content || "").trim().split(/\s+/).length;
      return words < 1000;
    });

    console.log(`🔄 Bulk rewrite: ${pending.length} blogs need rewriting (${blogs.length - pending.length} already done)`);
    const results: string[] = [];

    for (const blog of pending) {
      try {
        console.log(`  ✍️  Rewriting: "${blog.title}"`);
        const humanized = await humanizeWithRetry(blog.title, blog.content, blog.author);
        if (!humanized) throw new Error("No result returned");
        blog.title = humanized.title || blog.title;
        blog.content = humanized.content || blog.content;
        blog.excerpt = truncate(humanized.excerpt || blog.excerpt, 300);
        await blog.save();
        results.push(`✅ ${blog.title}`);
        console.log(`  ✅  Done: "${blog.title}"`);
        await wait(1500);
      } catch (err) {
        const msg = `❌ Failed: "${blog.title}" — ${String(err)}`;
        results.push(msg);
        console.error(msg);
      }
    }

    console.log("🏁 Bulk rewrite complete");
    res.json({
      success: true,
      total: blogs.length,
      rewritten: results.filter((r) => r.startsWith("✅")).length,
      skipped: blogs.length - pending.length,
      failed: results.filter((r) => r.startsWith("❌")).length,
      results,
    });
  } catch (err) {
    res.status(500).json({ success: false, message: String(err) });
  }
});

router.post("/generate/all", protect, async (_req: AuthRequest, res: Response) => {
  try {
    const results = await runManualGeneration();
    res.json({ success: true, data: results });
  } catch {
    res.status(500).json({ success: false, message: "Generation failed" });
  }
});

router.post("/generate/:categoryId", protect, async (req: AuthRequest, res: Response) => {
  try {
    const blog = await generateBlogForCategory(req.params.categoryId);
    res.json({ success: true, data: blog });
  } catch (err) {
    console.error("❌ Generation error:", err);
    res.status(500).json({ success: false, message: "Generation failed", error: String(err) });
  }
});

export default router;
